[package]
name = "plist"
version = "0.1.0"
authors = ["Gerrit Birkeland <gerrit@gerritbirkeland.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = "1"
clap = "2.3"
